//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\Personal\Projects\MBRDI\ExtractAndOffsetSurface\ExtractAndOffsetUI.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: snagareddy
//              Version: NX 12
//              Date: 07-01-2021  (Format: mm-dd-yyyy)
//              Time: 02:28 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using NXOpen;
using NXOpen.Assemblies;
using NXOpen.BlockStyler;
using NXOpen.Facet;
using NXOpen.Features;
using NXOpen.UF;
using NXOpen.UIStyler;
using Group = NXOpen.BlockStyler.Group;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class ExtractAndOffsetUI
{
    //class members
    private static Session theSession;
    private static UI theUI;

    private static Part workPart;
    private static UFSession theUfSession;
    private string theDlxFileName;
    private BlockDialog theDialog;
    private Group group0;// Block type: Group
    private FaceCollector SelectFaceBtn;// Block type: Face Collector
    
    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public ExtractAndOffsetUI()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theUfSession = UFSession.GetUFSession();
            workPart = theSession.Parts.Work;
            theDlxFileName = @"D:\Personal\Projects\MBRDI\ExtractAndOffsetSurface\ExtractAndOffsetSurface\ExtractAndOffsetSurface\ExtractAndOffsetUI.dlx";
            theDialog = theUI.CreateDialog(theDlxFileName);
            theDialog.AddApplyHandler(apply_cb);
            theDialog.AddOkHandler(ok_cb);
            theDialog.AddUpdateHandler(update_cb);
            theDialog.AddInitializeHandler(initialize_cb);
            theDialog.AddDialogShownHandler(dialogShown_cb);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static void Main()
    {
        ExtractAndOffsetUI theExtractAndOffsetUI = null;
        try
        {
            theExtractAndOffsetUI = new ExtractAndOffsetUI();
            // The following method shows the dialog immediately
            theExtractAndOffsetUI.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if(theExtractAndOffsetUI != null)
                theExtractAndOffsetUI.Dispose();
                theExtractAndOffsetUI = null;
        }
    }
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
     public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
         return Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }
    
    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //This method shows the dialog on the screen
    //------------------------------------------------------------------------------
    public DialogResponse Show()
    {
        try
        {
            theDialog.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if(theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }
    
    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            group0 = (Group)theDialog.TopBlock.FindBlock("group0");
            SelectFaceBtn = (FaceCollector)theDialog.TopBlock.FindBlock("SelectFaceBtn");
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;
        try
        {
            //---- Enter your callback code here -----
            //---- Enter your callback code here -----
            TaggedObject[] selectedObjects = SelectFaceBtn.GetSelectedObjects();
            string[] faceRules = SelectFaceBtn.GetDefaultFaceRulesMembers();
            string defaultFaceRulesAsString = SelectFaceBtn.DefaultFaceRulesAsString;
            List<Face> selectedFaces = new List<Face>(0);
            foreach (TaggedObject selectedObject in selectedObjects)
            {
                if (selectedObject is Face)
                {
                    // UFFacet ufFacet = theUfSession.Facet;
                    selectedFaces.Add(selectedObject as Face);
                }
            }

            if (selectedFaces.Any())
            {
                List<Body> extractFaces = ExtractFace(selectedFaces.ToArray());
                theSession.Parts.SetWork(workPart);
                FacetedBody[] facetBodies;
                int[] errTab;
                theSession.Parts.Work.FacetedBodies.CreateFacetBody(extractFaces.ToArray(), out facetBodies, out errTab);
                foreach (FacetedBody facetedBody in facetBodies)
                {
                    FacetedBody facetedBodyNx = theSession.Parts.Work.FacetedBodies.Copy(facetedBody, workPart, FacetedBodyCollection.Type.Nx);
                    facetedBodyNx.SetName("mine");
                    LocalOffsetBuilder localOffsetBuilder = theSession.Parts.Work.FacetedBodies.FacetModelingCollection.CreateLocalOffsetBuilder();
                    localOffsetBuilder.OffsetDistance.Value = 0.2;
                }
            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb( UIBlock block)
    {
        try
        {
            if(block == SelectFaceBtn)
            {
            //---------Enter your code here-----------
            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        int errorCode = 0;
        try
        {
            errorCode = apply_cb();
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist =null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }

    #region Custom Code

    public List<Body> ExtractFace(Face[] iFaces)
    {
        BasePart iFaceOwningPart = null;
        List<Body> extFaces = new List<Body>(0);
        Component iFaceOwningComponent = null;
        if (iFaces.Any())
        {
            Face iFace = iFaces[0];
            iFaceOwningPart = iFace.OwningPart;
            iFaceOwningComponent = iFace.OwningComponent;
        }

        if (iFaceOwningPart == null)
        {
            return extFaces;
        }

        PartLoadStatus loadStatus;
        //theSession.Parts.SetWorkComponent(iFaceOwningComponent, out loadStatus);

        ExtractFaceBuilder extractFaceBuilder1 = theSession.Parts.Work.Features.CreateExtractFaceBuilder(null);
        extractFaceBuilder1.ParentPart = ExtractFaceBuilder.ParentPartType.WorkPart;
        extractFaceBuilder1.DeleteHoles = false;
        extractFaceBuilder1.Associative = false;
        extractFaceBuilder1.FixAtCurrentTimestamp = false;
        extractFaceBuilder1.HideOriginal = false;
        extractFaceBuilder1.InheritDisplayProperties = false;
        extractFaceBuilder1.Type = ExtractFaceBuilder.ExtractType.Face;
        extractFaceBuilder1.ParentPart = ExtractFaceBuilder.ParentPartType.WorkPart;
        extractFaceBuilder1.FeatureOption = ExtractFaceBuilder.FeatureOptionType.OneFeatureForAllBodies;
        extractFaceBuilder1.FaceOption = ExtractFaceBuilder.FaceOptionType.FaceChain;

        Face[] boundaryFaces1 = new Face[0];
        FaceTangentRule faceTangentRule1;
        faceTangentRule1 = workPart.ScRuleFactory.CreateRuleFaceTangent(iFaces[0], boundaryFaces1, 0.5);

        SelectionIntentRule[] rules1 = new SelectionIntentRule[1];
        rules1[0] = faceTangentRule1;
        extractFaceBuilder1.FaceChain.ReplaceRules(rules1, false);


        NXObject nXObject1 = extractFaceBuilder1.Commit();
        extractFaceBuilder1.Destroy();



        if (nXObject1 != null)
        {
            ExtractFace extractedFace = nXObject1 as ExtractFace;

            if (extractedFace != null)
            {
                Body firstOrDefault = extractedFace.GetBodies().FirstOrDefault();
                
                extFaces.Add(firstOrDefault);
            }

            //if (extractedFace != null)
            //{
            //    Body firstOrDefault = extractedFace.GetBodies().FirstOrDefault();
            //    //Extract Faceted Bodies
            //    theSession.Parts.SetWork(workPart);


            //    FacetedBody[] facetBodies;
            //    int[] errorTable;
            //    FacetBodyFromBodyBuilder facetBodyFromBodyBuilder = workPart.FacetedBodies.FacetModelingCollection.CreateFacetBodyFromBodyBuilder();
            //    facetBodyFromBodyBuilder.Associative = false;
            //    facetBodyFromBodyBuilder.NonFacetedBodiesToConvert.Add(firstOrDefault);
            //    facetBodyFromBodyBuilder.OriginalBodyOption = FacetBodyFromBodyBuilder.OriginalBodyOptions.Keep;
            //    facetBodyFromBodyBuilder.OutputType = FacetBodyFromBodyBuilder.OutputTypes.NXFacetBody;
            //    if (facetBodyFromBodyBuilder.Validate())
            //    {
            //        NXObject nxObject = facetBodyFromBodyBuilder.Commit();
            //    }

            //    facetBodyFromBodyBuilder.Destroy();
            //    //CreateFacetBody(new Body[]{ firstOrDefault }, out facetBodies, out errorTable);
            //    //workPart.FacetedBodies.CreateFacetBodyFromFaces(new Face[] { iFace }, out facetBodies, out errorTable);
            //    //if (facetBodies.Length > 0)
            //    //{
            //    //    foreach (FacetedBody facetedBodyJt in facetBodies)
            //    //    {
            //    //       workPart.FacetedBodies.Convert(facetedBodyJt,  FacetedBodyCollection.Type.Nx);
            //    //    }
            //    //}

            //    //Delete Extracted Face

            //}
        }

        return extFaces;
    }

    public void ExtractFacesAsSingleFeature()
    {
        Session.UndoMarkId markId1;
        markId1 = theSession.SetUndoMark(Session.MarkVisibility.Visible, "Start");

        Feature nullNXOpen_Features_Feature = null;
        WavePointBuilder wavePointBuilder1;
        wavePointBuilder1 = workPart.Features.CreateWavePointBuilder(nullNXOpen_Features_Feature);

        WaveDatumBuilder waveDatumBuilder1;
        waveDatumBuilder1 = workPart.Features.CreateWaveDatumBuilder(nullNXOpen_Features_Feature);

        CompositeCurveBuilder compositeCurveBuilder1;
        compositeCurveBuilder1 = workPart.Features.CreateCompositeCurveBuilder(nullNXOpen_Features_Feature);

        ExtractFaceBuilder extractFaceBuilder1;
        extractFaceBuilder1 = workPart.Features.CreateExtractFaceBuilder(nullNXOpen_Features_Feature);

        MirrorBodyBuilder mirrorBodyBuilder1;
        mirrorBodyBuilder1 = workPart.Features.CreateMirrorBodyBuilder(nullNXOpen_Features_Feature);

        WaveSketchBuilder waveSketchBuilder1;
        waveSketchBuilder1 = workPart.Features.CreateWaveSketchBuilder(nullNXOpen_Features_Feature);

        compositeCurveBuilder1.CurveFitData.Tolerance = 0.01;

        compositeCurveBuilder1.CurveFitData.AngleTolerance = 0.5;

        extractFaceBuilder1.FaceOption = ExtractFaceBuilder.FaceOptionType.FaceChain;

        compositeCurveBuilder1.Associative = false;

        waveDatumBuilder1.ParentPart = WaveDatumBuilder.ParentPartType.WorkPart;

        wavePointBuilder1.ParentPart = WavePointBuilder.ParentPartType.WorkPart;

        extractFaceBuilder1.ParentPart = ExtractFaceBuilder.ParentPartType.WorkPart;

        mirrorBodyBuilder1.ParentPartType = MirrorBodyBuilder.ParentPart.WorkPart;

        compositeCurveBuilder1.ParentPart = CompositeCurveBuilder.PartType.WorkPart;

        waveSketchBuilder1.ParentPart = WaveSketchBuilder.ParentPartType.WorkPart;

        compositeCurveBuilder1.Associative = false;

        theSession.SetUndoMarkName(markId1, "Extract Geometry Dialog");

        compositeCurveBuilder1.Section.DistanceTolerance = 0.01;

        compositeCurveBuilder1.Section.ChainingTolerance = 0.0094999999999999998;

        compositeCurveBuilder1.Section.AngleTolerance = 0.5;

        compositeCurveBuilder1.Section.DistanceTolerance = 0.01;

        compositeCurveBuilder1.Section.ChainingTolerance = 0.0094999999999999998;

        extractFaceBuilder1.Associative = false;

        extractFaceBuilder1.FixAtCurrentTimestamp = false;

        extractFaceBuilder1.HideOriginal = false;

        extractFaceBuilder1.DeleteHoles = false;

        extractFaceBuilder1.InheritDisplayProperties = false;

        extractFaceBuilder1.Type = ExtractFaceBuilder.ExtractType.Face;

        Brep brep1 = (Brep)workPart.Features.FindObject("UNPARAMETERIZED_FEATURE(1)");
        Face face1 = (Face)brep1.FindObject("FACE 173 {(409.0808120428932,-323.9703830128203,793.0263564562007) UNPARAMETERIZED_FEATURE(1)}");
        Face[] boundaryFaces1 = new Face[0];
        FaceTangentRule faceTangentRule1;
        faceTangentRule1 = workPart.ScRuleFactory.CreateRuleFaceTangent(face1, boundaryFaces1, 0.5);

        SelectionIntentRule[] rules1 = new SelectionIntentRule[1];
        rules1[0] = faceTangentRule1;
        extractFaceBuilder1.FaceChain.ReplaceRules(rules1, false);

        Session.UndoMarkId markId2;
        markId2 = theSession.SetUndoMark(Session.MarkVisibility.Invisible, "Extract Geometry");

        theSession.DeleteUndoMark(markId2, null);

        Session.UndoMarkId markId3;
        markId3 = theSession.SetUndoMark(Session.MarkVisibility.Invisible, "Extract Geometry");

        NXObject nXObject1;
        nXObject1 = extractFaceBuilder1.Commit();

        theSession.DeleteUndoMark(markId3, null);

        theSession.SetUndoMarkName(markId1, "Extract Geometry");

        compositeCurveBuilder1.Destroy();

        waveDatumBuilder1.Destroy();

        wavePointBuilder1.Destroy();

        extractFaceBuilder1.Destroy();

        mirrorBodyBuilder1.Destroy();

        waveSketchBuilder1.Destroy();

        // ----------------------------------------------
        //   Menu: Tools->Journal->Stop Recording
        // ----------------------------------------------

    }

    #endregion

}
